### ISSUE TITLE
Version 6.0.1 Datagrid LoadData apply filter will cause unhandled exception

### ISSUE THREAD

**Issue by kirkone** [radzenhq/radzen-blazor#1965]
Today I updated my Blazor WebAssembly site to dotnet 9 and Radzen.Blazor 6.0.1.

I have a Datagrid with simple filter and implemented the LoadData as described here:
https://blazor.radzen.com/datagrid-loaddata.

The data loads fine but after i input something in a Filter field executing the query will silently break the LoadData Method.

I was able to see the Exeption in the devtools one time that was mentioning that it was not able to load `/System.Runtime.dll`.

I see it is working on the sample page, but I am not sure if this is already running on version 6.

Could it be related to this here:
https://forum.radzen.com/t/just-released-our-new-major-version-of-radzen-blazor-6-0-0-without-reference-to-system-linq-dynamic-core-nuget-package/19748
and this:
https://github.com/radzenhq/radzen-blazor/blob/53e746146bc680b6819987f80fcc72184aeeb18a/Radzen.Blazor/DynamicExtensions.cs#L33

Thank you for your help

**Comment by enchev** [comment]
Indeed our demos are running using latest version. Please provide runnable code demonstrating the problem.

**Comment by k-Sacr** [comment]
Also, all filters with the data type "enum" or "enum?" are broken

**Comment by k-Sacr** [comment]
oh, and also the filters "DateOnly", "DateOnly?", maybe "DateTime", "DateTime?" do not work

**Comment by enchev** [comment]
@k-Sacr We have such demos as well and all of them works normally. For example:
https://localhost:5001/datagrid-enum-filter

**Comment by k-Sacr** [comment]
> [@k-Sacr](https://github.com/k-Sacr) We have such demos as well and all of them works normally. For example: https://blazor.radzen.com/datagrid-enum-filter

Sorry, of course I meant when using LoadData.
Where dynamic linq was used.

**Comment by k-Sacr** [comment]
Quick demo: https://blazor.radzen.com/datagrid-loaddata

https://github.com/user-attachments/assets/e5f2bec2-4920-4b81-8417-857774806901

```
@using RadzenBlazorDemos.Data
@using RadzenBlazorDemos.Models.Northwind

@inherits DbContextPage

<RadzenButton Text="Reset" Click="@Reset" Style="margin-bottom: 20px;" />
<RadzenDataGrid FilterMode="FilterMode.Advanced" style="height: 335px" @ref="grid" IsLoading=@isLoading Count="@count" Data="@employees" LoadData="@LoadData" AllowSorting="true" AllowFiltering="true" AllowPaging="true" PageSize="4" PagerHorizontalAlign="HorizontalAlign.Center" ColumnWidth="200px">
    <Columns>
        <RadzenDataGridColumn Property="@nameof(Employee.EmployeeID)" Filterable="false" Title="ID" Frozen="true" Width="80px" TextAlign="TextAlign.Center" />
        <RadzenDataGridColumn Title="Photo" Frozen="true" Sortable="false" Filterable="false" Width="80px" TextAlign="TextAlign.Center" >
            <Template Context="data">
                <RadzenImage Path="@data.Photo" class="rz-gravatar" AlternateText="@(data.FirstName + " " + data.LastName)" />
            </Template>
        </RadzenDataGridColumn>
        <RadzenDataGridColumn Property="@nameof(Employee.FirstName)" Title="First Name" Frozen="true" Width="160px"/>
        <RadzenDataGridColumn Property="@nameof(Employee.LastName)" Title="Last Name" Width="160px"/>
        <RadzenDataGridColumn Property="@nameof(Employee.Title)" Title="Job Title" 
            Type="typeof(IEnumerable<string>)" FilterValue="@selectedTitles" FilterOperator="FilterOperator.Contains" Width="200px">
            <FilterTemplate>
                <RadzenDropDown @bind-Value=@selectedTitles Style="width:100%" InputAttributes="@(new Dictionary<string,object>(){ { "aria-label", "select title" }})"
                    Change=@OnSelectedTitlesChange Data="@(titles)" AllowClear="true" Multiple="true" />
            </FilterTemplate>
        </RadzenDataGridColumn>
        <RadzenDataGridColumn Property="@nameof(Employee.TitleOfCourtesy)" Title="Title" Width="120px" />
        <RadzenDataGridColumn Property="@nameof(Employee.BirthDate)" Title="Birth Date" FormatString="{0:d}" Width="160px" />
        <RadzenDataGridColumn Property="@nameof(Employee.HireDate)" Title="Hire Date" FormatString="{0:d}" Width="160px" />
        <RadzenDataGridColumn Property="@nameof(Employee.Address)" Title="Address" Width="200px" />
        <RadzenDataGridColumn Property="@nameof(Employee.City)" Title="City" Width="160px" />
        <RadzenDataGridColumn Property="@nameof(Employee.Region)" Title="Region" Width="160px" />
        <RadzenDataGridColumn Property="@nameof(Employee.PostalCode)" Title="Postal Code" Width="160px" />
        <RadzenDataGridColumn Property="@nameof(Employee.Country)" Title="Country" Width="160px" />
        <RadzenDataGridColumn Property="@nameof(Employee.HomePhone)" Title="Home Phone" Width="160px" />
        <RadzenDataGridColumn Property="@nameof(Employee.Extension)" Title="Extension" Width="160px" />
        <RadzenDataGridColumn Property="@nameof(Employee.Notes)" Title="Notes" Width="300px" />
    </Columns>
</RadzenDataGrid>

<RadzenCard class="rz-mt-6">
    <RadzenText TextStyle="TextStyle.H6" TagName="TagName.H2" class="rz-mb-4">Perform custom data-binding</RadzenText>
    <RadzenText TextStyle="TextStyle.Body1">
        1. Set the Data and Count properties.
    </RadzenText>
        <pre class="rz-mt-4 rz-p-4">
            <code>&lt;RadzenDataGrid Count="@@count" Data="@@employees"</code>
        </pre>
    <RadzenText TextStyle="TextStyle.Body1">
        2. Handle the LoadData event and update the Data and Count backing fields (<code>employees</code> and <code>count</code> in this case).
    </RadzenText>
        <pre class="rz-mt-4 rz-p-4">
            <code>
void LoadData(LoadDataArgs args)
{
    var query = dbContext.Employees.AsQueryable();

    if (!string.IsNullOrEmpty(args.Filter))
    {
        query = query.Where(grid.ColumnsCollection);
    }

    if (!string.IsNullOrEmpty(args.OrderBy))
    {
        query = query.OrderBy(args.OrderBy);
    }

    count = query.Count();

    employees = query.Skip(args.Skip.Value).Take(args.Top.Value).ToList();


} 
            </code>
        </pre>
</RadzenCard>
@code {
    RadzenDataGrid<Employee> grid;
    int count;
    IEnumerable<Employee> employees;
    bool isLoading = false;

    List<string> titles = new List<string> {"Sales Representative", "Vice President, Sales", "Sales Manager", "Inside Sales Coordinator" };
    IEnumerable<string> selectedTitles;

    async Task OnSelectedTitlesChange(object value)
    {
        if (selectedTitles != null && !selectedTitles.Any())
        {
            selectedTitles = null;  
        }
        
        await grid.FirstPage();
    }

    async Task Reset()
    {
        grid.Reset(true); 
        await grid.FirstPage(true);
    }

    async Task LoadData(LoadDataArgs args)
    {
        isLoading = true;

        await Task.Yield();

        var query = dbContext.Employees.AsQueryable();

        if (!string.IsNullOrEmpty(args.Filter))
        {
            // Filter via the Where method
            query = query.Where(grid.ColumnsCollection);
        }

        if (!string.IsNullOrEmpty(args.OrderBy))
        {
            // Sort via the OrderBy method
            query = query.OrderBy(args.OrderBy);
        }

        // Important!!! Make sure the Count property of RadzenDataGrid is set.
        count = query.Count();

        // Perform paging via Skip and Take.
        employees = query.Skip(args.Skip.Value).Take(args.Top.Value).ToList();

        isLoading = false;
    }
}

```

**Comment by enchev** [comment]
I was able to replicate it - let's put this in a separate issue since this is not related to not finding System.Runtime.dll.

**Comment by k-Sacr** [comment]
> I was able to replicate it - let's put this in a separate issue since this is not related to not finding System.Runtime.dll. As a workaround you can use Where(grid.ColumnCollection) similar to our LoadData demo.

Thx

I understand the reason for dropping the System.Linq.Dynamic.Core dependency, but unfortunately, this change broke all our DataGrid in the project.
But Dynamic LINQ provided support for a wide range of filtering variations, and its removal has significantly impacted functionality.

**Comment by enchev** [comment]
You can still use Dynamic LINQ if you reference it in your project.

**Comment by k-Sacr** [comment]
> You can still use Dynamic LINQ if you reference it in your project.

Yes, but that won't fix the DataGrid, will it? I haven't tried it yet.

We use DataGrid with LoadData via ToFilterString (which used dynamic linq if I'm not mistaken), otherwise we would have to write each filter manually.

**Comment by enchev** [comment]
ToFilterString() will output a string that can work in both our extension method and Dynamic LINQ methods:
https://forum.radzen.com/t/just-released-our-new-major-version-of-radzen-blazor-6-0-0-without-reference-to-system-linq-dynamic-core-nuget-package/19748?u=enchev
When you reference System.Linq.Dynamic.Core, their method will be picked instead of ours.

**Comment by k-Sacr** [comment]
> ToFilterString() will output a string that can work in both our extension method and Dynamic LINQ methods: https://forum.radzen.com/t/just-released-our-new-major-version-of-radzen-blazor-6-0-0-without-reference-to-system-linq-dynamic-core-nuget-package/19748?u=enchev When you reference System.Linq.Dynamic.Core, their method will be picked instead of ours.

tried this, i get exception:
System.InvalidOperationException: "Invalid Where selector".

6.0.1 Dont work:

![Image](https://github.com/user-attachments/assets/e9476f98-6d22-4cc7-8f0d-e04fe87f8feb)

5.9 Work:

![Image](https://github.com/user-attachments/assets/e64657b0-66fd-4035-9456-234c4eda7677)

Unfortunately I can't provide a demo code quickly, but this is a regular column with the DateOnly type

**Comment by enchev** [comment]
The problem with Dates is already fixed and it will be release later today:
https://github.com/radzenhq/radzen-blazor/commit/60a3789e9c701d9ea06fd97212cfabc3aaab1514

**Comment by kirkone** [comment]
Is the current documentation site running on version 6 already?

**Comment by enchev** [comment]
Yes, it's running latest version as always.

**Comment by kirkone** [comment]
Is it also running on dotnet 9?

**Comment by enchev** [comment]
Yes. Maybe you should check the code for reference.

**Comment by bdovaz** [comment]
> > ToFilterString() will output a string that can work in both our extension method and Dynamic LINQ methods: https://forum.radzen.com/t/just-released-our-new-major-version-of-radzen-blazor-6-0-0-without-reference-to-system-linq-dynamic-core-nuget-package/19748?u=enchev When you reference System.Linq.Dynamic.Core, their method will be picked instead of ours.
> 
> tried this, i get exception: System.InvalidOperationException: "Invalid Where selector".
> 
> 6.0.1 Dont work:
> 
> ![Image](https://github.com/user-attachments/assets/e9476f98-6d22-4cc7-8f0d-e04fe87f8feb)
> 
> 5.9 Work:
> 
> ![Image](https://github.com/user-attachments/assets/e64657b0-66fd-4035-9456-234c4eda7677)
> 
> Unfortunately I can't provide a demo code quickly, but this is a regular column with the DateOnly type

Same problem:

6.0.3 (FAILS): 

it => RoleNames.Contains("testRoleName")

5.9.9 (WORKS): 

RoleNames.Contains("testRoleName")

**Comment by enchev** [comment]
The example works correctly with both filtering and sorting. We cannot do much if we cannot reproduce the problem - you can debug also your app using our source code and submit pull request with a fix.

**Comment by bdovaz** [comment]
> The example works correctly with both filtering and sorting. We cannot do much if we cannot reproduce the problem - you can debug also your app using our source code and submit pull request with a fix.

I base myself on `LoadData` example that I have put in my previous message and in the case of a field that is of type `IEnumerable<string>` I base myself on this other example to make a custom filter: https://blazor.radzen.com/datagrid-filter-template?theme=material3

Specifically the `Custom filtering template with Custom Command` example.

If you look at that example @enchev, the filter of the column `Work Status` has stopped working, something has happened in 6.x that has broken that example and it will have relation in part with what happens to me.

**Comment by enchev** [comment]
@bdovaz I see now what you are after - we will do our best to provide fix for this case ASAP.

**Comment by kirkone** [comment]
> Yes. Maybe you should check the code for reference. [@kirkone](https://github.com/kirkone) Can you verify if Radzen.Blazor 6.0.3 works for your case?

I am not able to reproduce the runtime.dll error.
But found something new:
Using simple filter mode filtering on columns works if every row has a value in in this column.
If there is a null value in at least one row it brakes.

**Comment by enchev** [comment]
@kirkone  is the row (data item itself) null or the property value?

**Comment by kirkone** [comment]
only the value regarding to the column where the filter has applied is null in my case. Columns where every row has a value in this field are working.

**Comment by enchev** [comment]
All reported problems in this thread are fixed in Radzen.Blazor 6.0.4 and I'm closing this. Please open separate issues if you find something else.

**Comment by kirkone** [comment]
> All reported problems in this thread are fixed in Radzen.Blazor 6.0.4 and I'm closing this. Please open separate issues if you find something else.

Thanks for the fix.

I still have issues with some columns but i cannot see what the difference between the working ones is.
I will investigate further and will open a new issue with the details.

**Comment by bdovaz** [comment]
> All reported problems in this thread are fixed in Radzen.Blazor 6.0.4 and I'm closing this. Please open separate issues if you find something else.

@enchev the error I mention in this example still exists:

> https://blazor.radzen.com/datagrid-filter-template?theme=material3
> 
> Specifically the `Custom filtering template with Custom Command` example.

![Image](https://github.com/user-attachments/assets/9a913cb3-f632-47b0-87f3-b4fd55161c43)

**Comment by enchev** [comment]
@bdovaz Interesting, it works locally but not when deployed - I'll check it immediately.

**Comment by bdovaz** [comment]
No problem I'm still on 5.x, I have a PR with renovate for 6.x so it will update itself then you release a new 6.x with a fix.

Thanks!

**Comment by enchev** [comment]
@bdovaz I've updated the demo for now to use strongly typed expressions until we have solution for strings.

**Comment by enchev** [comment]
@bdovaz Both the functionality and the demo are restored in our just released 6.0.7 version.
