### ISSUE TITLE
Make "orderBy" public in RadzenGrid (or some way of setting the initial orderby status)

### ISSUE THREAD

**Issue by javiercampos** [radzenhq/radzen-blazor#75]
**Is your feature request related to a problem? Please describe.**
I can't seem to set the initial state of the sorting on columns. In our "search" pages (where we use the grid, mainly), we store the "search model" where we save the current page, search form status, etc.

We'd like to also store the sorting on the grid (we use the `LoadData` event). However, there's an `orderBy` property from where the sorting state is stored, but it's private (it's also what the column header template queries to draw its icon), so we can't modify it.

You have the `OrderBy` and `OrderByDescending` methods which set the property, but they also set the current page to 0 (they set `Skip` to 0) and immediately request a reload... so setting the current page number and the sorting state doesn't seem to be possible without initiating several `LoadData` requests.

It's of course hackable if you know what you are doing (or we can just copy the source code and modify), but this should be able to be native to the component, in our oppinion.

**Describe the solution you'd like**
Either make `orderBy` public, or make it a `[Parameter]` property which can be set on initialization without necessarily invoking a reload (or set the page to first page).

Notice that if making it a parameter it would clash with the `OrderBy` method, so it should be named differently

If you need it, I offer myself to do the PR if needed, as long as you decide what we should call the public property (which again, can't be `OrderBy` because there's a method named like that)

**Comment by enchev** [comment]
Hi @javiercampos,

In my opinion we will need a bit more complex implementation - for example property for every column for current sort state similar to filtering related properties. We will do our best to provide it soon!

**Comment by akorchev** [comment]
Should be addressed in the new RadzenDataGrid component. Here is a demo that shows how to set the sort state of a column: https://blazor.radzen.com/datagrid-sort-api

**Comment by javiercampos** [comment]
Please note that this does not solve the problem, cecause: 

a) `SortOrder` is a parameter and can only (or should, you get a warning otherwise) be assigned on the markup, unless you build the complete view from a `RenderView` delegate, and 
b) setting `SortOrder` on a column (even if doing it via reflection) does not update the grid's `sorts` variable (which makes the descriptors), so even after setting the `SortOrder` of the columns programatically (which does not call `OnSetParameters` on the column), the grid does not reflect the update, so the call to `LoadData` doesn't include the actual sorting, unless you specify it on first render, on the markup.

The worst part is that there is a whole system to change the order, both in the datagrid, and the columns themselves, but everything is internal or private, and there's no public API for it (which is what was needed here).

**Comment by javiercampos** [comment]
Btw, just as a hack, I've currently solved it using reflection to access the internal methods and properties... this is what I do:

To store the state:
```                var getSortOrderMethod = Grid.ColumnsCollection[0].GetType().GetMethod("GetSortOrder",
                                             BindingFlags.Instance | BindingFlags.NonPublic) ??
                                         throw new InvalidOperationException("No GetSortOrder method on column");
                GridCurrentSort = Grid.ColumnsCollection.Select(x => (SortOrder?) (getSortOrderMethod.Invoke(x, null)))
                    .ToArray();```

Then store `GridCurrentSort` somewhere. Note that `GetSortOrder` is an internal method. You can access the `SortOrder` parameter, but that's not updated when the user changes the sorting (it's only there for the initial markup-defined sorting, and never gets updated afterwards).

Restoring it is a little more complicated... first, we need to call `SetSortOrder` on each column to set its sort order (it's again, an internal method). Setting `SortOrder` programatically won't work because it does not raise `SetParameter` on the blazor lifecycle:
``` 
// Retrieve the above's GridCurrentSort from somewhere
var setSortOrderMethod = Grid.ColumnsCollection[0].GetType().GetMethod("SetSortOrder",
                 BindingFlags.Instance | BindingFlags.NonPublic, null,
                 new Type[] {typeof(SortOrder?)}, null) ??
             throw new Exception("No column set sort order method found");
for (var i = 0; i < GridCurrentSort.Length; i++)
{
    if (GridCurrentSort[i] is not null)
    {
        setSortOrderMethod.Invoke(Grid.ColumnsCollection[i], new object?[] {GridCurrentSort[i]});
    }
}
```

This is not enough... the grid doesn't know (it only updates on its internal events) the actual order, so we need to make a `SortDescriptor` list and assign it to its (again, internal, with no public API) `sorts` field, so we do that. To do it properly (although we could extract the SortOrder from the stored one), we again, have to call `GetSortOrder` (another internal) on the column, so we need to access two internal things here, the `GetSortOrder` method on the column, and the `sorts` field on the actual grid:
```var getSortOrderMethod = Grid.ColumnsCollection[0].GetType().GetMethod("GetSortOrder",
                             BindingFlags.Instance | BindingFlags.NonPublic) ??
                         throw new Exception("No column get sort order  method found");
var sorts = Grid.ColumnsCollection
    .Where(c => c.Sortable && c.Visible && (SortOrder?) getSortOrderMethod.Invoke(c, null) != null)
    .Select(c => new SortDescriptor()
    {
        Property = c.GetSortProperty(),
        SortOrder = ((SortOrder?) getSortOrderMethod.Invoke(c, null))!.Value,
    }).ToList();
var fld = Grid.GetType().GetField("sorts", BindingFlags.Instance | BindingFlags.NonPublic)  ??
          throw new Exception("No sorts descriptor field found");
fld.SetValue(Grid, sorts);```

This seems to work fine... but of course, using a non-public API will make you be extremely careful on future updates.

I'd love a public API for this to be able to *read and set* everything *programatically*, and not just on the Blazor markup definition.

Having it as is, might work for specific cases (where you can store the parameters and bind them in your component), but not when you want to do something generic.
